#+TITLE: Continuous Integration Microservice
#+AUTHOR: VLEAD
#+DATE: [2017-06-05 MON]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ../org-templates/level-1.org
#+options: ^:nil
#+LATEX: Literal LaTeX code for export

* Application: 
  A lab is currently defined as a set of related experiments and is a web
  application. Each lab is a repository on github. To ensure evolution of
  software and solicit contribution from folks across the world, continuous
  integration will be used around each lab.This continuous integration
  microservice automates the building, testing and deploying of
  applications. Projects created by a single individual or entire teams can use
  this service to automate the integration process. A cycle for integration
  will involve building the code, running the unit test cases, hosting the
  application and running the integration tests. Each integration is verified
  by an automated build (including test) to detect integration errors as
  quickly as possible. Many teams find that this approach leads to
  significantly reduced integration problems and allows a team to develop
  cohesive software more rapidly.
  
* Functional Requirements:
  ** Automactically clone the updated repository from Github.
  ** Build the required repository and run the respective testcases.
  ** Report the errors generated incase certain testcases don't successfully run.
  ** Host the generated Doc files on the respective server.

* Shortlisted Tools
  ** Jenkins
  ** BuildBot
  ** Go CD
  ** Drone
  ** Travis
  ** Tox


